import type { PantryItem, Recipe, Scan, ShoppingList } from '@/types/api';

export const demoScans: Scan[] = [
  {
    id: 'demo-scan-1',
    user_id: 'guest-demo',
    image_path: '/demo/fridge-1.jpg',
    ingredients: [
      { name: 'Eggs', quantity: '6', confidence: 0.95 },
      { name: 'Spinach', quantity: '1 bag', confidence: 0.91 },
      { name: 'Parmesan', quantity: '100g', confidence: 0.88 },
    ],
    status: 'completed',
    created_at: '2026-02-10T09:30:00Z',
    updated_at: '2026-02-10T09:31:00Z',
  },
  {
    id: 'demo-scan-2',
    user_id: 'guest-demo',
    image_path: '/demo/fridge-2.jpg',
    ingredients: [
      { name: 'Chicken breast', quantity: '2 fillets', confidence: 0.93 },
      { name: 'Bell pepper', quantity: '2', confidence: 0.89 },
      { name: 'Yogurt', quantity: '1 cup', confidence: 0.86 },
    ],
    status: 'completed',
    created_at: '2026-02-09T18:45:00Z',
    updated_at: '2026-02-09T18:46:00Z',
  },
  {
    id: 'demo-scan-3',
    user_id: 'guest-demo',
    image_path: '/demo/fridge-3.jpg',
    ingredients: [
      { name: 'Tomatoes', quantity: '4', confidence: 0.94 },
      { name: 'Pasta', quantity: '200g', confidence: 0.9 },
      { name: 'Garlic', quantity: '3 cloves', confidence: 0.87 },
    ],
    status: 'completed',
    created_at: '2026-02-08T13:12:00Z',
    updated_at: '2026-02-08T13:13:00Z',
  },
];

export const demoRecipes: Recipe[] = [
  {
    id: 'demo-recipe-1',
    user_id: 'guest-demo',
    scan_id: 'demo-scan-1',
    title: 'Creamy Spinach Omelette',
    description: 'Fast, protein-rich breakfast with pantry staples.',
    ingredients: [
      { name: 'Eggs', amount: '3', available: true },
      { name: 'Spinach', amount: '1 cup', available: true },
      { name: 'Parmesan', amount: '2 tbsp', available: true },
      { name: 'Butter', amount: '1 tsp', available: false },
    ],
    instructions: [
      'Whisk eggs with a pinch of salt and pepper.',
      'Saute spinach in a non-stick pan for 1 minute.',
      'Pour in eggs, cook on low heat, then fold with parmesan.',
      'Serve hot with toast or salad.',
    ],
    cook_time: 12,
    servings: 2,
    difficulty: 'easy',
    is_favorite: true,
    times_made: 4,
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'demo-recipe-2',
    user_id: 'guest-demo',
    scan_id: 'demo-scan-2',
    title: 'Smoky Chicken Pepper Skillet',
    description: 'One-pan dinner with bold flavor in under 30 minutes.',
    ingredients: [
      { name: 'Chicken breast', amount: '2 fillets', available: true },
      { name: 'Bell pepper', amount: '2', available: true },
      { name: 'Yogurt', amount: '1/2 cup', available: true },
      { name: 'Paprika', amount: '1 tsp', available: false },
    ],
    instructions: [
      'Slice chicken and peppers into strips.',
      'Season chicken and sear in a hot skillet until browned.',
      'Add peppers and cook until softened.',
      'Stir in yogurt off heat for a creamy finish.',
    ],
    cook_time: 28,
    servings: 2,
    difficulty: 'medium',
    is_favorite: false,
    times_made: 2,
    created_at: '2026-02-09T19:00:00Z',
  },
  {
    id: 'demo-recipe-3',
    user_id: 'guest-demo',
    scan_id: 'demo-scan-3',
    title: 'Garlic Tomato Weeknight Pasta',
    description: 'Comforting pasta with minimal ingredients.',
    ingredients: [
      { name: 'Pasta', amount: '200g', available: true },
      { name: 'Tomatoes', amount: '4', available: true },
      { name: 'Garlic', amount: '3 cloves', available: true },
      { name: 'Olive oil', amount: '1 tbsp', available: false },
    ],
    instructions: [
      'Boil pasta in salted water until al dente.',
      'Cook garlic in olive oil until fragrant.',
      'Add chopped tomatoes and simmer 8 to 10 minutes.',
      'Toss with pasta and serve.',
    ],
    cook_time: 22,
    servings: 3,
    difficulty: 'easy',
    is_favorite: false,
    times_made: 6,
    created_at: '2026-02-08T13:30:00Z',
  },
];

export const demoPantryItems: PantryItem[] = [
  {
    id: 'demo-pantry-1',
    user_id: 'guest-demo',
    name: 'Eggs',
    quantity: '12',
    category: 'Dairy & Eggs',
    added_at: '2026-02-10T07:00:00Z',
  },
  {
    id: 'demo-pantry-2',
    user_id: 'guest-demo',
    name: 'Tomatoes',
    quantity: '5',
    category: 'Produce',
    added_at: '2026-02-09T14:20:00Z',
  },
  {
    id: 'demo-pantry-3',
    user_id: 'guest-demo',
    name: 'Pasta',
    quantity: '1 box',
    category: 'Grains & Pasta',
    added_at: '2026-02-09T14:25:00Z',
  },
  {
    id: 'demo-pantry-4',
    user_id: 'guest-demo',
    name: 'Greek yogurt',
    quantity: '500g',
    category: 'Dairy & Eggs',
    added_at: '2026-02-08T16:00:00Z',
  },
  {
    id: 'demo-pantry-5',
    user_id: 'guest-demo',
    name: 'Spinach',
    quantity: '1 bag',
    category: 'Produce',
    added_at: '2026-02-08T16:15:00Z',
  },
  {
    id: 'demo-pantry-6',
    user_id: 'guest-demo',
    name: 'Chicken breast',
    quantity: '2 fillets',
    category: 'Meat & Seafood',
    added_at: '2026-02-07T18:05:00Z',
  },
];

export const demoShoppingLists: ShoppingList[] = [
  {
    id: 'demo-list-1',
    user_id: 'guest-demo',
    name: 'Weekend Brunch',
    items: [
      { name: 'Sourdough bread', amount: '1 loaf', checked: true, category: 'Bakery' },
      { name: 'Avocados', amount: '3', checked: false, category: 'Produce' },
      { name: 'Cherry tomatoes', amount: '1 box', checked: false, category: 'Produce' },
    ],
    created_at: '2026-02-11T11:00:00Z',
    updated_at: '2026-02-11T11:00:00Z',
  },
  {
    id: 'demo-list-2',
    user_id: 'guest-demo',
    name: 'Pasta Night',
    items: [
      { name: 'Olive oil', amount: '1 bottle', checked: false, category: 'Pantry Staples' },
      { name: 'Parmesan', amount: '150g', checked: false, category: 'Dairy & Eggs' },
      { name: 'Basil', amount: '1 bunch', checked: true, category: 'Produce' },
    ],
    created_at: '2026-02-10T19:30:00Z',
    updated_at: '2026-02-10T19:30:00Z',
  },
];
